package com.thoughtworks.cruise.tlb;

/**
 * @understands TBL constants
 */
public interface TlbConstants {
    
    String CRUISE_SERVER_URL = "CRUISE_SERVER_URL";
    String CRUISE_PIPELINE_NAME = "CRUISE_PIPELINE_NAME";
    String CRUISE_STAGE_NAME = "CRUISE_STAGE_NAME";
    String CRUISE_JOB_NAME = "CRUISE_JOB_NAME";
    String CRUISE_STAGE_COUNTER = "CRUISE_STAGE_COUNTER";
    String CRUISE_PIPELINE_COUNTER = "CRUISE_PIPELINE_COUNTER";
    String CRUISE_PIPELINE_LABEL = "CRUISE_PIPELINE_LABEL";
    String PASSWORD = "TLB_PASSWORD";
    String USERNAME = "TLB_USERNAME";
    String TLB_CRITERIA = "TLB_CRITERIA";
}
